### ISSUE TITLE
Return None instead of raising exceptions

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-python#32] opened 2019-07-18 13:12 UTC
Most of our methods raise exceptions if the model can't produce an embedding for the given input, e.g. `embedding()` and `similarity()` while we could also return `None` in those cases.

I'm not sure what's canonical Python here, but I'd prefer to do something like:
```Python
embedding = embeds.Embedding("something oov")
if embedding is None:
    embedding = generic_oov_embed()
```
over
```Python
try:
    embedding = embeds.Embedding("something oov")
except KeyError:
    embedding = generic_oov_embed()
```

What's your take on this?

**Comment by twuebi** [comment] 2019-07-18 13:26
I wasn't asked, still here's my take:

AFAIK, the usage of exceptions in python isn't frowned upon as much as in other languages. A dictionary, for instance, also communicates that a key is unknown through `KeyError` which leads to this pattern:

~~~python
try:
    some_dict[key] += 1
except KeyError:
    some_dict[key] = 1
~~~

It could also be done like this:

~~~python
some_dict[key] = some_dict.get(key, 1) + 1
~~~

but I've seen both versions.

**Comment by danieldk** [comment] 2019-07-18 13:36
I guess it would be best to follow the conventions of the standard library here: throw an exception indexing that fails, return `None` from methods. Of course, a distinction should be made between absent values and errors. E.g. trying to do a similarity query on a matrix that does not support them (non-view `Storage`) should always lead to an exception.

**Comment by danieldk** [comment] 2019-07-18 13:44
> ```python
> try:
>     some_dict[key] += 1
> except KeyError:
>     some_dict[key] = 1
> ```

I know this is common in Python (and 'student Java'), but I don't like it, because it leads to two lookups. And in a language with virtually no optimization like Python, there is also no hope of getting optimized away. Also, in many languages exceptions do have a certain amount of overhead.

```
some_dict[key] = some_dict.get(key, 1) + 1
```

Of course, this has the same problem ;).

Of course, it does not apply here, since we don't do lookups with mutation anyway.

**Comment by twuebi** [comment] 2019-07-18 13:50
> I know this is common in Python (and 'student Java'), but I don't like it, because it leads to two lookups. And in a language with virtually no optimization like Python, there is also no hope of getting optimized away. Also, in many languages exceptions do have a certain amount of overhead.

That'd be only on insertion, right?



The other options:

~~~python
some_dict[key] = some_dict.get(key, 1) + 1
~~~

and

~~~python
if key in some_dict:
    some_dict[key] += 1
else:
    some_dict[key] = 1
~~~

both perform two lookups for everything.

____________________

Anyways, what's your preferred way?

**Comment by RealNicolasBourbaki** [comment] 2019-07-18 14:40
Emmm... Exceptions in python are not that costly as they are in C++ or Java. As far as I know, python culture is generally in favor of exception (and maybe sometimes people do it little bit too much, but I think we are not). I would prefer the way we are doing right now.

**Comment by danieldk** [comment] 2019-07-18 15:13
> Anyways, what's your preferred way?

I don't really care for Python and don't write much Python (outside constructing Tensorflow graphs). Most other languages have good solutions to this, e.g. by returning an entry object (like Rust) or using closures to do in-place creation/updates.

But in this particular case the problem is that Python `int`s are immutable. If the value type is some immutable type, then you could just

```
a = foo.get("blah", Bar())
a.some_mutable_method()
```

Though, I don't know if the second argument is lazily evaluated (it would at least be possible, since `dict` is a build-in), if not you have a different cost center. Someone has probably created a mutable integer type.

**Comment by danieldk** [comment] 2019-07-18 15:44
> Emmm... Exceptions in python are not that costly

On a Core i5 8259U:

* Return `None` and check with `if`: 0.07 usec
* Throw an exception and catch it: 0.24 usec

More than 3 times more expensive is costly. In languages with algebraic data types, the cost of returning an error is the same as returning success. But people probably don't care, because everything is expensive in Python.

In the Python case, the actual performance in the `dict` case depends on how often you expect a key not to be present, since if the key is present, no exception is raised.

> as they are in C++

Actually, in deeper stacks, C++ exceptions are faster than value returns. For less deep stacks it depends on a lot of factors (including the compiler and ABI).

> I would prefer the way we are doing right now.

Which is not Pythonic, since Python uses values for e.g. `dict.get`. Also, as Sebiastian aptly demonstrated, the proposed change leads to cleaner code.

**Comment by sebpuetz** [comment] 2019-07-18 16:31
> I wasn't asked, still here's my take:
> 
> AFAIK, the usage of exceptions in python isn't frowned upon as much as in other languages. A dictionary, for instance, also communicates that a key is unknown through `KeyError` which leads to this pattern:
> 
> ```python
> try:
>     some_dict[key] += 1
> except KeyError:
>     some_dict[key] = 1
> ```

I think there's a difference between those cases. When you index using square brackets, even Rust will panic, and I'm fine with that behaviour with this type of lookup. 

The problem I'm seeing here is that the `.embedding()` method - which could be seen as pendant to `.get()` on Python `dict`s - raises an exception when the model can't produce an embedding.  `Embeddings` itself doesn't implement `__getitem__` which, if we did implement it, should then raise an exception if no embedding can be produced.

> I don't really care for Python and don't write much Python (outside constructing Tensorflow graphs). 
> Most other languages have good solutions to this, e.g. by returning an entry object (like Rust) or 
> using closures to do in-place creation/updates.

I'm taking this as no opposition to changing the return types?

**Comment by danieldk** [comment] 2019-07-18 17:12
> I'm taking this as no opposition to changing the return types?

I am completely in favor!

**Comment by danieldk** [comment] 2019-07-24 13:08
Fixed in #38

**Comment by twuebi** [comment] 2019-10-07 22:24
I just spent 15 minutes figuring out where the nans come from.

```py
mat = np.zeros([batch_size, max_len, 300])
for idx, text in enumerate(texts):
    for t_idx, token in enumerate(text):
        mat[idx, t_idx,:] = embeddings.embedding(token)
```

sets all OOV columns to `nan`. This fails very silently I'd prefer the exception over it. Of course this is only happening due to Python..

**Comment by danieldk** [comment] 2019-10-08 06:05
The `embedding` method mirrors the interface of `dict.get`. You would get the same behavior if your data is in a dict. We should keep an exception-free code path and this is it. However, I am in favor of being able to provide a default argument like `dict.get`. You could set this to to `0.0`, some vector for unknowns, or some type that cannot be stored in a numpy array (to get an exception).

**Closed as completed** 2019-10-14 16:24 UTC
